### ISSUE TITLE
Update to support MosaicLayout

### ISSUE THREAD

**Issue by dzanot** [googleapis/java-monitoring-dashboards#260]
**Is your feature request related to a problem? Please describe.**
I am writing a tool to generate dashboards for some of our services, and would like the flexability of the mosaic layout.

**Describe the solution you'd like**
Update the protos to include the mosaic layout.

**Describe alternatives you've considered**
Using the `gcloud` cli (which presumably is the most up to date) via external process calls, not the greatest solution

**Additional context**
The mosaic layout is defined in the docs here: https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.dashboard.v1#google.monitoring.dashboard.v1.MosaicLayout

**Comment by suztomo** [comment]
https://github.com/googleapis/google-cloud-java/blob/main/java-monitoring-dashboards/proto-google-cloud-monitoring-dashboard-v1/src/main/java/com/google/monitoring/dashboard/v1/MosaicLayout.java exists.
